# SPDX-FileCopyrightText: 2021 David Ruescas <david@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "braid"
version = "0.4.0"
authors = [
  "David Ruescas <david@sequentech.io>",
  "Eduardo Robles <edu@sequentech.io>"
]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
rand = "0.8"
getrandom = { version = "0.2" }

strand = { path="../strand", features=["rayon"] }
b3 = { path="../b3", features = ["client"] }
# borsh = { version = "=1.5.1", features = ["derive"] }
crepe = "0.1.5"
strum = { version = "0.26.3", features = ["derive"] }
rayon = { version = "1.5" }

# grpc client
tonic = "0.12.1"

# trustee local store
rusqlite = { version = "0.32.1", features = ["bundled"] }

# only needed for verifier
serde_json = "1.0.105"
colored = "2.0.4"

# daemon
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.40.0" }
# uuid = { version = "1.2", features = ["v4"] }
rustc-hash = "2.0.0"

# logging
log = "0.4.17"
tracing = "0.1"
tracing-log = { version = "0.1.3" }
tracing-attributes = "0.1.23"
tracing-subscriber = "0.3.16"
tracing-tree = "0.2.1"

cfg-if = "1.0"
# config = {version = "0.13.1" }
hex = "0.4.2"
base64 = "0.22.1"
serde = "1.0.152"
toml = "0.6.0"
anyhow = "1.0"
thiserror = "1.0.50"

# wasm
wasm-bindgen-rayon = {version = "1.0.3", features = ["no-bundler"], optional = true}
wasm-bindgen = {version = "=0.2.79", optional = true}
tracing-wasm = {version="0.2.1", optional = true}

# dbg
reedline-repl-rs = { version = "1.0.7" }
ascii_table = { version = "4.0.2" }
async-trait = "0.1.73"

# profile memory
tikv-jemallocator = {version = "0.6.0", optional = true }
tikv-jemalloc-ctl = { version = "0.6.0", features = ["stats"], optional = true }

[dev-dependencies]
criterion = {version = "0.4", features=["html_reports"]}
serial_test = "2.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# wasm = ["dep:wasm-bindgen", "dep:wasm-bindgen-rayon", "dep:tracing-wasm", "instant/wasm-bindgen"]
fips_core = ["strand/fips_core"]
fips_full = ["strand/fips_full"]
rug = ["strand/rug"]
jemalloc = ["dep:tikv-jemalloc-ctl", "dep:tikv-jemallocator"]